//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jelo : Proizvod
    {
        public string Sastojci { get; set; }
        public string KuvarJmbg { get; set; }
    
        public virtual Kuvar Kuvar { get; set; }
    }
}
