//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupuje
    {
        public string NudiRestoranNaziv { get; set; }
        public string NudiProizvodNaziv { get; set; }
        public string KupacJmbg { get; set; }
        public string KonobarJmbg { get; set; }
    
        public virtual Nudi Nudi { get; set; }
        public virtual Kupac Kupac { get; set; }
        public virtual Konobar Konobar { get; set; }
    }
}
