//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestoranDbModelContainer : DbContext
    {
        public RestoranDbModelContainer()
            : base("name=RestoranDbModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vlasnik> Vlasnici { get; set; }
        public virtual DbSet<Restoran> Restorani { get; set; }
        public virtual DbSet<Radnik> Radnici { get; set; }
        public virtual DbSet<Kupac> Kupci { get; set; }
        public virtual DbSet<Proizvod> Proizvodi { get; set; }
        public virtual DbSet<Nudi> Nudis { get; set; }
        public virtual DbSet<Kupuje> Kupovine { get; set; }
    }
}
